//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class WEU_OWAESEntities : DbContext
{
    public WEU_OWAESEntities()
        : base("name=WEU_OWAESEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<vwWarrantInfo> vwWarrantInfoes { get; set; }
    public virtual DbSet<LOG> LOGs { get; set; }
    public virtual DbSet<vwLastSuccessfulUpdate> vwLastSuccessfulUpdates { get; set; }
}
