//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPF.OWAES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwWarrantInfo
    {
        public string WarrantNo { get; set; }
        public string PersonIDNo { get; set; }
        public string SummonsNo { get; set; }
        public string CaseTypeDescription { get; set; }
        public string MsgContent { get; set; }
    }
}
